In [2]:
import numpy as np

The definition of advanced indexing means that x[(1, 2, 3),] is fundamentally different than x[(1, 2, 3)]. The latter is equivalent to x[1, 2, 3] which will trigger basic selection while the former will trigger advanced indexing.

#### Integer array indexing

In [3]:
x = np.arange(10, 1, -1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [4]:
x[np.array([3, 3, 1, 8])]

array([7, 7, 9, 2])

In [5]:
# If the index values are out of bounds then an IndexError is thrown:

x = np.array([[1, 2], [3, 4], [5, 6]])
x[np.array([1, -1])]

array([[3, 4],
       [5, 6]])

In [7]:
x[np.array([3, 4])]   # Error

IndexError: index 3 is out of bounds for axis 0 with size 3

Advanced indices always are broadcast and iterated as one:

In [8]:
'''
result[i_1, ..., i_M] == x[ind_1[i_1, ..., i_M], ind_2[i_1, ..., i_M],
                           ..., ind_N[i_1, ..., i_M]]
            
'''

'\nresult[i_1, ..., i_M] == x[ind_1[i_1, ..., i_M], ind_2[i_1, ..., i_M],\n                           ..., ind_N[i_1, ..., i_M]]\n            \n'

In [9]:
y = np.arange(35).reshape(5, 7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [12]:
y[np.array([0, 2, 4]), np.array([0, 1, 2])]

# """
#      In this example, the first index value is 0 for both index arrays, 
#      and thus the first value of the resultant array is y[0, 0]. 
#      The next value is y[2, 1], and the last is y[4, 2].
# """

array([ 0, 15, 30])

 If they cannot be broadcast to the same shape, an exception is raised:

In [13]:
y[np.array([0, 2, 4]), np.array([0, 1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [14]:
# For example if we just use one index array with y:

y[np.array([0, 2, 4])]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

#### Boolean array indexing

This advanced indexing occurs when obj is an array object of Boolean type, such as may be returned from comparison operators. A single boolean index array is practically identical to x[obj.nonzero()] where, as described above, obj.nonzero() returns a tuple (of length obj.ndim) of integer index arrays showing the True elements of obj. However, it is faster when obj.shape == x.shape.

A common use case for this is filtering for desired element values. For example, one may wish to select all entries from an array which are not NaN:

In [15]:
x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])
x[~np.isnan(x)]

array([1., 2., 3.])

Or wish to add a constant to all negative elements:

In [16]:
x = np.array([1., -1., -2., 3])
x[x < 0] += 20
x

array([ 1., 19., 18.,  3.])

In [17]:
# x[ind_1, boolean_array, ind_2] is equivalent to x[(ind_1,) + boolean_array.nonzero() + (ind_2,)].

In [18]:
x = np.arange(35).reshape(5, 7)
b = x > 20
b[:, 5]

array([False, False, False,  True,  True])

In [19]:
x[b[:, 5]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

Here the 4th and 5th rows are selected from the indexed array and combined to make a 2-D array.

#### Combining advanced and basic indexing

When there is at least one slice (:), ellipsis (...) or newaxis in the index (or the array has more dimensions than there are advanced indices), then the behaviour can be more complicated. 

In [20]:
y = np.arange(35).reshape(5,7)
y[np.array([0, 2, 4]), 1:3]

array([[ 1,  2],
       [15, 16],
       [29, 30]])

In [21]:
y[:, 1:3][np.array([0, 2, 4]), :]


array([[ 1,  2],
       [15, 16],
       [29, 30]])

In [22]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
x[1:2, 1:3]


array([[4, 5]])

In [23]:
x[1:2, [1, 2]]

array([[4, 5]])

Two cases of index combination need to be distinguished:

The advanced indices are separated by a slice, Ellipsis or newaxis. For example x[arr1, :, arr2].

The advanced indices are all next to each other. For example x[..., arr1, arr2, :] but not x[arr1, :, 1] since 1 is an advanced index in this regard.